### PR TITLE
fix: resource separation inside conditional loops to avoid templating issue when operator webhook  disabled

### PR DESCRIPTION
**Pull request by Carlosgova**
## Pull request description

Fix the resource separator character to be inside the conditional loops to avoid adding extra separators when the webhook/preUpgrade  section is disabled, which creates issues with the templating.

## Checklist (choose whats happened)

- [ ] breaking change! (describe)
- [ ] tested locally
- [ ] tested on cluster
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

## Breaking changes

- No

## Changes

-

## Fixes

- testkube-operator issues with role,rolebinding,ServiceAccount resource separtation when webhook/PreUpgrade is disabled.

### CODE REVIEW

**Review by vsukhin — APPROVED** [review]
Looks good.Thank you @Carlosgova 
@ypoplavs please check

**Comment by ypoplavs** [comment]
Hello @Carlosgova! thank you for the contribution! 
It looks good, however, could you please let me know the scenarios you use when you encounter issues with templating? We will be checking from our side as well.

Thank you!

**Comment by Carlosgova** [comment]
@ypoplavs thanks!
Sure, with our helm templating scripts we are running into weird errors due to the extra separation characters ('---') that are added when Webhook is disabled for testkube-operator -> https://github.com/kubeshop/helm-charts/blob/main/charts/testkube-operator/templates/rolebinding.yaml#L94

We have some external tooling that does not work with empty yaml documents rendered in the Helm Chart templating output.

**Review by nicufk — APPROVED** [review]

**Comment by ypoplavs** [comment]
Thank you @Carlosgova! We can merge it, however, one more thing - could you please create a pull request to a `develop` branch instead of `main`? We have moved to a new gitflow that requires changes to be deployed to `develop` firstly.

**Comment by Carlosgova** [comment]
@ypoplavs 
Sure! created PR and linked it with this one.
QQ, is there an ETA for when this would be merged into main and tagged?
Thanks!

**Comment by ypoplavs** [comment]
Merged it @Carlosgova! We're testing new features at the moment and planning to release any time soon (today or tomorrow).

**Pull request closed without merging**
