### PR TITLE
fix: install common TestWorkflowTemplates in the context of testkube-api

### PR DESCRIPTION
**Pull request by rangoo94**
## Pull request description 

- to make it working for multi-namespace agents, which don't have `testkube-operator` enabled (`testkube-operator.enabled=false`)

## Checklist (choose whats happened)

- [ ] breaking change! (describe)
- [ ] tested locally
- [ ] tested on cluster
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

### CODE REVIEW

**Review by tkonieczny — APPROVED** [review]

**Comment by devantler** [comment]
This seems to be a breaking change:

```
Warning  InstallFailed     2m21s  helm-controller  Helm install failed for release testkube/testkube with chart testkube@1.17.27: failed post-install: unable to build kubernetes object for deleting hook testkube/charts/testkube-api/templates │
│ /testworkflows/builtin-templates/artillery.yaml: resource mapping not found for name: "official--artillery--beta" namespace: "" from "": no matches for kind "TestWorkflowTemplate" in version "testworkflows.testkube.io/v1"                       │
│ ensure CRDs are installed first     
```

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: testkube
spec:
  interval: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: testkube
      version: 1.17.27
      sourceRef:
        kind: HelmRepository
        name: testkube
  # https://github.com/kubeshop/helm-charts/blob/develop/charts/testkube/values.yaml
  values:
    testkube-api:
      uiIngress:
        enabled: true
        hosts:
          - testkube.${cluster_domain}
        path: /v1 # This is required for the ingress to work per https://github.com/kubeshop/helm-charts/issues/428#issuecomment-1873973628
    testkube-dashboard:
      ingress:
        enabled: true
        hosts:
          - testkube.${cluster_domain}
      apiServerEndpoint: testkube.${cluster_domain}${cluster_ingress_port:=}
```

We are using Flux GitOps, which is configured to always use the latest CRDs. This fails during install and not during an upgrade, as we run our workloads in CI before we apply any changes. So I would imagine this is an issue for most.

Do you have any mitigation/fix?

**Comment by rangoo94** [comment]
Thanks @devantler for the report, it shouldn't be a breaking change. @tkonieczny, could you check?

**Comment by devantler** [comment]
Could it be that the testkube-operator was not bumped?

https://github.com/kubeshop/helm-charts/commit/cf990c28c128f9f662cbb072a10e896908d186e8

**Comment by tkonieczny** [comment]
@rangoo94 I just checked rechecked the installation, and everything seems fine (chart: `testkube-1.17.27`). I will check other cases

**Comment by devantler** [comment]
@tkonieczny did you replicate this? It is quite consistent here, and I can hear from another person in my org that they are experiencing the same error. They are also using Flux.

**Pull request merged**
