### PR TITLE
feat: allow custom probes for testkube-api (#417)

### LINKED ISSUE #417: Allow modification of readiness and liveness probe parameters of the testkube-api deployment
**Is your feature request related to a problem? Please describe.**
I tried installing testkube using the helm charts. When starting the application, I see that requests are being throttled towards the Kubernetes Control Plane in my cluster. After a while, the testkube-api app starts running, but is terminated externally with a terminate signal.

**Describe the solution you'd like**
I suspect that the readiness and liveness probes were set too sharply. To test this I would like to change the readiness and liveness probes for the testkube-api deployment. The helm chart currently does not offer any option to do that.

**Describe alternatives you've considered**
You can change the deployment manually after installing it through helm, but that's not a good way.

**Additional context**
testkube-api-startup-error

### PR DESCRIPTION
**Pull request by zaljic**
## Pull request description 
This allows the configuration of custom liveness and readiness probes for the testkube-api

## Checklist (choose whats happened)

- [ ] breaking change! (describe)
- [x] tested locally
- [ ] tested on cluster
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

## Breaking changes

No breaking changes.

## Changes

- Templated liveness and readiness probes in testkube-api deployment to allow custom values

## Fixes
#417

### CODE REVIEW

**Comment by zaljic** [comment]
How do I test this?

**Review by nicufk — APPROVED** [review]
Looks good, Good Job!

**Comment by zaljic** [comment]
@nicufk thanks for the info! Will do that

**Comment by zaljic** [comment]
Btw, I think this might make sense for all apps. After this is merged, I will create another PR if you think this is a good addition.

**Review by vsukhin — APPROVED** [review]
looks good, please also copy them to values-demo.yaml and values-stage.yaml

**Comment by zaljic** [comment]
> looks good, please also copy them to values-demo.yaml and values-stage.yaml

Done

**Comment by vsukhin** [comment]
@zaljic let us know, if local testing was successful, then we can merge it

**Comment by zaljic** [comment]
> @zaljic let us know, if local testing was successful, then we can merge it

Local testing was successful

**Pull request merged**
