### PR TITLE
Change template to use local variable first instead of global

### LINKED ISSUE #536: Local values are not taken at all if global is set
**Describe the bug**
With https://github.com/kubeshop/helm-charts/commit/6f69e0056b5dcdbf0efbca024246a12ec9ba9d27 commit I observed regression in our testkube instance. We are using only local registries on our clusters (as we don't have an internet access there) and for each kind of registry (docker.io, gcr.io) we have separate url. As docker.io is the most common one we used that value as a global one and for each other registry we overwritten them using "local" variables. As far as I understand helm values local ones should overwrite global ones, but right now it's not available. We observed that on operator-pre-upgrade job.

**To Reproduce**
1. Run `helm template . --set="global.imageRegistry=test"`
2. Check that all images uses "test" registry

**Expected behavior**
If local variables are set the default/global variable should be overwritten

**Version / Cluster**
- Which testkube version? 1.12.9

### PR DESCRIPTION
**Pull request by michal-jagiello-tmpl**
## Pull request description 
Fix #536 

## Checklist (choose whats happened)

- [ ] breaking change! (describe)
- [ ] tested locally
- [ ] tested on cluster
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

## Breaking changes

-

## Changes

-

## Fixes

-

### CODE REVIEW

**Comment by michal-jagiello-tmpl** [comment]
that change allows me to run the newest version of testkube on my local environment

**Comment by vsukhin** [comment]
thank you @michal-jagiello-tmpl we need to wait a bit, when the maintaner of this repo is back from vacation

**Comment by michal-jagiello-tmpl** [comment]
Any update?

**Comment by vsukhin** [comment]
@ypoplavs should be back on Monday

**Comment by michal-jagiello-tmpl** [comment]
Guys, any update?

**Comment by ypoplavs** [comment]
Hello @michal-jagiello-tmpl!
I will reach the team for discussion and get back to you.

**Comment by michal-jagiello-tmpl** [comment]
Looks like with latest version it's not needed anymore

**Pull request closed without merging**
