### PR TITLE
chore: delete OAuth support for CLI

### PR DESCRIPTION
**Pull request by rangoo94**
## Pull request description 

* https://github.com/kubeshop/testkube/pull/6013

## Checklist (choose whats happened)

- [ ] breaking change! (describe)
- [ ] tested locally
- [ ] tested on cluster
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

### CODE REVIEW

**Comment by thradec** [comment]
Hi, we were using direct cli access without oauth and now the ingress definition is gone. Is direct access still supported?

**Comment by vsukhin** [comment]
hey, @thradec No, direct access feature was not touched, we just remove existed cli oauth support, because it was limited and it looked no one used it. Do you think ingress definition is useful for you @rangoo94 @ypoplavs ?

**Comment by thradec** [comment]
Hi, we were using direct access and call testkube api from outside the cluster, so the calls go through ingress which is exposing the api. Or should we migrate to ui-ingress now?

For context, this is the example how we are using it:
```
$ testkube --client direct --api-uri https://<cluster-hostname>/testkube/api run tw <test-workflow>
```

**Comment by rangoo94** [comment]
@emil2k, @ypoplavs - could you recommend?

We've been earlier having [**Ingress**](https://github.com/kubeshop/helm-charts/pull/956/files#diff-3f4fb72b6357b943ee7f146c9290d77e14ff9f9ca5eb29ce9cfc5d365220df42L2-L58) created based on the `cliIngress` property. I'm not sure what was the original intent around that - I'm not sure if it's safe to expose it this way. It was not enabled by default though.

We can either:
* add it back, and just delete oauth configuration from there
* recommend adding `Ingress` resource separately

I think that it may be better to add `Ingress` separately, but I have limited knowledge about that.

**Comment by rangoo94** [comment]
@emil2k, @ypoplavs - if you think that it's fine to keep `cliIngress` property, I have prepared [**helm-charts#962**](https://github.com/kubeshop/helm-charts/pull/962/files) PR that will add this functionality back 👍

**Comment by rangoo94** [comment]
@thradec - I have added back `cliIngress`, as it seems to not cause any problems as it's disabled by default. The newest Helm Charts should work fine for you 👍

**Comment by thradec** [comment]
Thanks a lot! ❤️

**Pull request merged**
