### PR TITLE
Initial resource requests for core resources

### PR DESCRIPTION
**Pull request by tkonieczny**
Initial resource requests for core resources (based on running multiple dozen resource-hungry tests, mainly K6 - 2 GETs without loop delay). They should improve testkube's responsivness under high load. Initial values - the goal is to adjust them over time.

```
No load:
NAME                                                   CPU(cores)   MEMORY(bytes)   
testkube-api-server-77d68fb5fc-gnpvg                   1m           10Mi            
testkube-dashboard-794596b5dc-nxdvn                    1m           2Mi             
testkube-minio-testkube-64cd475b94-glxxg               1m           96Mi            
testkube-mongodb-6c9c5db4d5-4hr92                      52m          159Mi           
testkube-operator-controller-manager-7788959c5-ddqml   2m           17Mi

testkube-api-server-77d68fb5fc-gnpvg                   1m           10Mi
testkube-dashboard-794596b5dc-nxdvn                    1m           2Mi
testkube-minio-testkube-64cd475b94-glxxg               1m           97Mi
testkube-mongodb-6c9c5db4d5-4hr92                      27m          160Mi
testkube-operator-controller-manager-7788959c5-ddqml   12m          17Mi

150VU
NAME                                                   CPU(cores)   MEMORY(bytes)
6308abdf016ae39e42614f0c-zrmpk                         299m         262Mi
testkube-api-server-77d68fb5fc-gnpvg                   12m          18Mi
testkube-dashboard-794596b5dc-nxdvn                    1m           2Mi
testkube-minio-testkube-64cd475b94-glxxg               1m           97Mi
testkube-mongodb-6c9c5db4d5-4hr92                      31m          117Mi
testkube-operator-controller-manager-7788959c5-ddqml   11m          21Mi

200vu:
NAME                                                   CPU(cores)   MEMORY(bytes)
6308abdf016ae39e42614f0c-zrmpk                         327m         301Mi
testkube-api-server-77d68fb5fc-gnpvg                   13m          18Mi
testkube-dashboard-794596b5dc-nxdvn                    1m           2Mi
testkube-minio-testkube-64cd475b94-glxxg               1m           97Mi
testkube-mongodb-6c9c5db4d5-4hr92                      31m          117Mi
testkube-operator-controller-manager-7788959c5-ddqml   11m          21Mi

200vu+ - ramp up
NAME                                                   CPU(cores)   MEMORY(bytes)
6308af79016ae39e42614f11-j7hhb                         1094m        296Mi
testkube-api-server-77d68fb5fc-gnpvg                   8m           17Mi
testkube-dashboard-794596b5dc-nxdvn                    1m           2Mi
testkube-minio-testkube-64cd475b94-glxxg               1m           97Mi
testkube-mongodb-6c9c5db4d5-4hr92                      28m          94Mi
testkube-operator-controller-manager-7788959c5-ddqml   12m          20Mi

ramp up aboce 200vu is very slow and is not able to met requirements

500vu:
NAME                                                   CPU(cores)   MEMORY(bytes)
6308aed1016ae39e42614f0f-djs92                         366m         367Mi
testkube-api-server-77d68fb5fc-gnpvg                   12m          18Mi
testkube-dashboard-794596b5dc-nxdvn                    1m           2Mi
testkube-minio-testkube-64cd475b94-glxxg               1m           97Mi
testkube-mongodb-6c9c5db4d5-4hr92                      55m          118Mi
testkube-operator-controller-manager-7788959c5-ddqml   11m          20Mi

5*200vu:
NAME                                                   CPU(cores)   MEMORY(bytes)
6308b03e016ae39e42614f14-w7hng                         214m         163Mi
6308b041016ae39e42614f16-2295x                         265m         162Mi
6308b044016ae39e42614f18-xkhrs                         310m         164Mi
6308b046016ae39e42614f1a-k9dzk                         226m         159Mi
6308b048016ae39e42614f1c-cgrfg                         227m         157Mi
testkube-api-server-77d68fb5fc-gnpvg                   53m          17Mi
testkube-dashboard-794596b5dc-nxdvn                    1m           2Mi
testkube-minio-testkube-64cd475b94-glxxg               1m           98Mi
testkube-mongodb-6c9c5db4d5-4hr92                      38m          94Mi
testkube-operator-controller-manager-7788959c5-ddqml   11m          20Mi
NAME                                                   CPU(cores)   MEMORY(bytes)
6308b03e016ae39e42614f14-w7hng                         71m          172Mi
6308b041016ae39e42614f16-2295x                         149m         173Mi
6308b044016ae39e42614f18-xkhrs                         89m          170Mi
6308b046016ae39e42614f1a-k9dzk                         68m          171Mi
6308b048016ae39e42614f1c-cgrfg                         84m          169Mi
testkube-api-server-77d68fb5fc-gnpvg                   50m          17Mi
testkube-dashboard-794596b5dc-nxdvn                    1m           2Mi
testkube-minio-testkube-64cd475b94-glxxg               1m           97Mi
testkube-mongodb-6c9c5db4d5-4hr92                      43m          94Mi
testkube-operator-controller-manager-7788959c5-ddqml   11m          20Mi
NAME                                                   CPU(cores)   MEMORY(bytes)
6308b03e016ae39e42614f14-w7hng                         79m          178Mi
6308b041016ae39e42614f16-2295x                         70m          173Mi
6308b044016ae39e42614f18-xkhrs                         87m          172Mi
6308b046016ae39e42614f1a-k9dzk                         86m          172Mi
6308b048016ae39e42614f1c-cgrfg                         85m          171Mi
testkube-api-server-77d68fb5fc-gnpvg                   52m          17Mi
testkube-dashboard-794596b5dc-nxdvn                    1m           2Mi
testkube-minio-testkube-64cd475b94-glxxg               1m           97Mi
testkube-mongodb-6c9c5db4d5-4hr92                      27m          94Mi
testkube-operator-controller-manager-7788959c5-ddqml   12m          20Mi
NAME                                                   CPU(cores)   MEMORY(bytes)
6308b03e016ae39e42614f14-w7hng                         87m          182Mi
6308b041016ae39e42614f16-2295x                         95m          180Mi
6308b044016ae39e42614f18-xkhrs                         106m         182Mi
6308b046016ae39e42614f1a-k9dzk                         93m          176Mi
6308b048016ae39e42614f1c-cgrfg                         89m          175Mi
testkube-api-server-77d68fb5fc-gnpvg                   50m          17Mi
testkube-dashboard-794596b5dc-nxdvn                    1m           2Mi
testkube-minio-testkube-64cd475b94-glxxg               1m           98Mi
testkube-mongodb-6c9c5db4d5-4hr92                      49m          94Mi
testkube-operator-controller-manager-7788959c5-ddqml   11m          20Mi
after execution:
NAME                                                   CPU(cores)   MEMORY(bytes)
testkube-api-server-77d68fb5fc-gnpvg                   49m          17Mi
testkube-dashboard-794596b5dc-nxdvn                    1m           2Mi
testkube-minio-testkube-64cd475b94-glxxg               1m           98Mi
testkube-mongodb-6c9c5db4d5-4hr92                      48m          95Mi
testkube-operator-controller-manager-7788959c5-ddqml   12m          19Mi


20*200vu
NAME                                                   CPU(cores)   MEMORY(bytes)
6308b2f7016ae39e42614f1e-zf8mh                         80m          157Mi
6308b2f8016ae39e42614f20-mkfbb                         86m          154Mi
6308b2fa016ae39e42614f22-tzd9q                         102m         148Mi
6308b2fb016ae39e42614f24-kkghx                         85m          138Mi
6308b2fc016ae39e42614f26-qmz9k                         69m          106Mi
6308b2fe016ae39e42614f28-8mbch                         71m          127Mi
6308b2ff016ae39e42614f2a-vfmtq                         68m          96Mi
6308b301016ae39e42614f2c-842sn                         57m          53Mi
6308b302016ae39e42614f2e-v5c8w                         71m          90Mi
6308b304016ae39e42614f30-zw7kz                         74m          64Mi
6308b306016ae39e42614f32-w4l6q                         86m          62Mi
6308b307016ae39e42614f34-tf9tn                         0m           49Mi
6308b309016ae39e42614f36-nxh78                         0m           42Mi
6308b30a016ae39e42614f38-kkmkb                         0m           36Mi
6308b30c016ae39e42614f3a-587fb                         0m           33Mi
6308b30d016ae39e42614f3c-mkrss                         0m           31Mi
6308b30e016ae39e42614f3e-lqw5z                         0m           31Mi
6308b310016ae39e42614f40-p98vv                         0m           19Mi
6308b312016ae39e42614f42-qjktp                         0m           30Mi
6308b314016ae39e42614f44-rgv89                         0m           19Mi
testkube-api-server-77d68fb5fc-gnpvg                   106m         20Mi
testkube-dashboard-794596b5dc-nxdvn                    1m           2Mi
testkube-minio-testkube-64cd475b94-glxxg               2m           98Mi
testkube-mongodb-6c9c5db4d5-4hr92                      66m          107Mi
testkube-operator-controller-manager-7788959c5-ddqml   11m          20Mi

(4 test failed)
NAME                                                   CPU(cores)   MEMORY(bytes)
6308b2fc016ae39e42614f26-qmz9k                         72m          152Mi
6308b2fe016ae39e42614f28-8mbch                         74m          151Mi
6308b2ff016ae39e42614f2a-vfmtq                         65m          144Mi
6308b301016ae39e42614f2c-842sn                         70m          136Mi
6308b302016ae39e42614f2e-v5c8w                         73m          142Mi
6308b304016ae39e42614f30-zw7kz                         72m          118Mi
6308b306016ae39e42614f32-w4l6q                         96m          130Mi
6308b307016ae39e42614f34-tf9tn                         58m          109Mi
6308b309016ae39e42614f36-nxh78                         72m          116Mi
6308b30a016ae39e42614f38-kkmkb                         71m          125Mi
6308b30c016ae39e42614f3a-587fb                         61m          117Mi
6308b30d016ae39e42614f3c-mkrss                         69m          107Mi
6308b30e016ae39e42614f3e-lqw5z                         77m          85Mi
6308b310016ae39e42614f40-p98vv                         85m          77Mi
6308b312016ae39e42614f42-qjktp                         67m          107Mi
6308b314016ae39e42614f44-rgv89                         83m          64Mi
testkube-api-server-77d68fb5fc-gnpvg                   103m         20Mi
testkube-dashboard-794596b5dc-nxdvn                    1m           2Mi
testkube-minio-testkube-64cd475b94-glxxg               1m           97Mi
testkube-mongodb-6c9c5db4d5-4hr92                      80m          88Mi
testkube-operator-controller-manager-7788959c5-ddqml   11m          20Mi

(2 more tests failed)
NAME                                                   CPU(cores)   MEMORY(bytes)
6308b2fc016ae39e42614f26-qmz9k                         86m          161Mi
6308b2fe016ae39e42614f28-8mbch                         89m          160Mi
6308b2ff016ae39e42614f2a-vfmtq                         87m          158Mi
6308b304016ae39e42614f30-zw7kz                         70m          159Mi
6308b306016ae39e42614f32-w4l6q                         81m          159Mi
6308b307016ae39e42614f34-tf9tn                         117m         158Mi
6308b309016ae39e42614f36-nxh78                         102m         157Mi
6308b30a016ae39e42614f38-kkmkb                         76m          160Mi
6308b30c016ae39e42614f3a-587fb                         96m          161Mi
6308b30d016ae39e42614f3c-mkrss                         58m          159Mi
6308b30e016ae39e42614f3e-lqw5z                         98m          158Mi
6308b310016ae39e42614f40-p98vv                         107m         159Mi
6308b312016ae39e42614f42-qjktp                         114m         159Mi
6308b314016ae39e42614f44-rgv89                         104m         160Mi
testkube-api-server-77d68fb5fc-gnpvg                   144m         22Mi
testkube-dashboard-794596b5dc-nxdvn                    1m           2Mi
testkube-minio-testkube-64cd475b94-glxxg               2m           98Mi
testkube-mongodb-6c9c5db4d5-4hr92                      91m          116Mi
testkube-operator-controller-manager-7788959c5-ddqml   28m          20Mi
$ testkube get execution 6308b302016ae39e42614f2e
W0826 13:59:02.698912   62997 gcp.go:120] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
ID:         6308b302016ae39e42614f2e
Name        stress-low-200vu-14
Number:            14
Test name:         stress-low-200vu
Type:              k6/script
Status:            failed
Start time:        2022-08-26 11:48:18.939 +0000 UTC
End time:          2022-08-26 11:50:07.392 +0000 UTC
Duration:          00:01:48

Status test execution failed:

⨯ container "6308b302016ae39e42614f2e" in pod "6308b302016ae39e42614f2e-v5c8w" is terminated
NAME                                                   CPU(cores)   MEMORY(bytes)
6308b2fc016ae39e42614f26-qmz9k                         26m          167Mi
6308b2fe016ae39e42614f28-8mbch                         27m          163Mi
6308b2ff016ae39e42614f2a-vfmtq                         33m          160Mi
6308b304016ae39e42614f30-zw7kz                         27m          162Mi
6308b306016ae39e42614f32-w4l6q                         26m          165Mi
6308b307016ae39e42614f34-tf9tn                         25m          165Mi
6308b309016ae39e42614f36-nxh78                         28m          159Mi
6308b30a016ae39e42614f38-kkmkb                         26m          162Mi
6308b30c016ae39e42614f3a-587fb                         38m          162Mi
6308b30d016ae39e42614f3c-mkrss                         28m          162Mi
6308b30e016ae39e42614f3e-lqw5z                         49m          162Mi
6308b310016ae39e42614f40-p98vv                         39m          161Mi
6308b312016ae39e42614f42-qjktp                         26m          164Mi
6308b314016ae39e42614f44-rgv89                         46m          164Mi
testkube-api-server-77d68fb5fc-gnpvg                   102m         21Mi
testkube-dashboard-794596b5dc-nxdvn                    1m           2Mi
testkube-minio-testkube-64cd475b94-glxxg               2m           98Mi
testkube-mongodb-6c9c5db4d5-4hr92                      30m          90Mi
testkube-operator-controller-manager-7788959c5-ddqml   12m          20Mi
execution finished:
NAME                                                   CPU(cores)   MEMORY(bytes)
testkube-api-server-77d68fb5fc-gnpvg                   1m           21Mi
testkube-dashboard-794596b5dc-nxdvn                    1m           2Mi
testkube-minio-testkube-64cd475b94-glxxg               10m          99Mi
testkube-mongodb-6c9c5db4d5-4hr92                      32m          92Mi
testkube-operator-controller-manager-7788959c5-ddqml   12m          20Mi

200-vu-incorrect-variable (a lot of output)
NAME                                                   CPU(cores)   MEMORY(bytes)
6308b7df016ae39e42614f47-tclrz                         920m         242Mi
testkube-api-server-77d68fb5fc-gnpvg                   43m          21Mi
testkube-dashboard-794596b5dc-nxdvn                    1m           2Mi
testkube-minio-testkube-64cd475b94-glxxg               1m           99Mi
testkube-mongodb-6c9c5db4d5-4hr92                      39m          93Mi
testkube-operator-controller-manager-7788959c5-ddqml   11m          20Mi
NAME                                                   CPU(cores)   MEMORY(bytes)
6308b7df016ae39e42614f47-tclrz                         956m         394Mi
testkube-api-server-77d68fb5fc-gnpvg                   12m          21Mi
testkube-dashboard-794596b5dc-nxdvn                    1m           2Mi
testkube-minio-testkube-64cd475b94-glxxg               1m           99Mi
testkube-mongodb-6c9c5db4d5-4hr92                      26m          93Mi
testkube-operator-controller-manager-7788959c5-ddqml   11m          21Mi
NAME                                                   CPU(cores)   MEMORY(bytes)
6308b7df016ae39e42614f47-tclrz                         765m         571Mi
testkube-api-server-77d68fb5fc-gnpvg                   18m          20Mi
testkube-dashboard-794596b5dc-nxdvn                    1m           2Mi
testkube-minio-testkube-64cd475b94-glxxg               1m           98Mi
testkube-mongodb-6c9c5db4d5-4hr92                      53m          90Mi
testkube-operator-controller-manager-7788959c5-ddqml   15m          20Mi


stress-high-1000vu
NAME                                                   CPU(cores)   MEMORY(bytes)
6308b7df016ae39e42614f47-tclrz                         60m          627Mi
6308b8d6016ae39e42614f4a-kswfb                         53m          55Mi
6308b8d8016ae39e42614f4c-7wvc2                         44m          61Mi
6308b8da016ae39e42614f4e-87xqn                         54m          49Mi
6308b8dc016ae39e42614f50-68fns                         66m          41Mi
6308b8de016ae39e42614f52-c9dst                         31m          42Mi
6308b8e0016ae39e42614f54-m4lng                         0m           28Mi
6308b8e2016ae39e42614f56-tjx6h                         0m           26Mi
testkube-api-server-77d68fb5fc-gnpvg                   139m         23Mi
testkube-dashboard-794596b5dc-nxdvn                    1m           2Mi
testkube-minio-testkube-64cd475b94-glxxg               2m           98Mi
testkube-mongodb-6c9c5db4d5-4hr92                      83m          113Mi
testkube-operator-controller-manager-7788959c5-ddqml   18m          19Mi
NAME                                                   CPU(cores)   MEMORY(bytes)
6308b7df016ae39e42614f47-tclrz                         35m          629Mi
6308b8d6016ae39e42614f4a-kswfb                         73m          67Mi
6308b8d8016ae39e42614f4c-7wvc2                         80m          64Mi
6308b8da016ae39e42614f4e-87xqn                         75m          59Mi
6308b8dc016ae39e42614f50-68fns                         35m          59Mi
6308b8de016ae39e42614f52-c9dst                         60m          60Mi
6308b8e0016ae39e42614f54-m4lng                         32m          49Mi
6308b8e2016ae39e42614f56-tjx6h                         67m          59Mi
6308b8e5016ae39e42614f58-bzlfn                         0m           19Mi
6308b8e7016ae39e42614f5a-gzrnr                         61m          45Mi
6308b8e9016ae39e42614f5c-krkhr                         0m           22Mi
6308b8eb016ae39e42614f5e-4h2tz                         0m           29Mi
6308b8ed016ae39e42614f60-74ph7                         0m           14Mi
6308b8ef016ae39e42614f62-wlq4g                         68m          39Mi
6308b8f1016ae39e42614f64-9xff9                         38m          35Mi
6308b8f3016ae39e42614f66-c7fhl                         0m           15Mi
6308b8f5016ae39e42614f68-pcnmw                         0m           15Mi
6308b8f7016ae39e42614f6a-dhkwd                         0m           1Mi
6308b8fa016ae39e42614f6c-gvwpf                         0m           0Mi
6308b8fc016ae39e42614f6e-ld6t6                         0m           6Mi
6308b8ff016ae39e42614f70-txgdl                         0m           7Mi
testkube-api-server-77d68fb5fc-gnpvg                   70m          22Mi
testkube-dashboard-794596b5dc-nxdvn                    1m           2Mi
testkube-minio-testkube-64cd475b94-glxxg               1m           98Mi
testkube-mongodb-6c9c5db4d5-4hr92                      56m          94Mi
testkube-operator-controller-manager-7788959c5-ddqml   10m          19Mi
NAME                                           CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
gke-testkube-test-default-pool-f08e8aa1-k4r3   1993m        212%   3157Mi          112%
NAME                                                   CPU(cores)   MEMORY(bytes)
6308b8dc016ae39e42614f50-68fns                         57m          180Mi
6308b8e2016ae39e42614f56-tjx6h                         87m          145Mi
6308b8e5016ae39e42614f58-bzlfn                         62m          89Mi
6308b8e9016ae39e42614f5c-krkhr                         63m          107Mi
6308b8eb016ae39e42614f5e-4h2tz                         50m          145Mi
6308b8ed016ae39e42614f60-74ph7                         76m          116Mi
6308b8ef016ae39e42614f62-wlq4g                         66m          67Mi
6308b8f1016ae39e42614f64-9xff9                         55m          76Mi
6308b8f3016ae39e42614f66-c7fhl                         61m          69Mi
6308b8f5016ae39e42614f68-pcnmw                         46m          78Mi
6308b8f7016ae39e42614f6a-dhkwd                         49m          60Mi
6308b8fa016ae39e42614f6c-gvwpf                         75m          59Mi
6308b8fc016ae39e42614f6e-ld6t6                         67m          127Mi
6308b8ff016ae39e42614f70-txgdl                         64m          60Mi
testkube-api-server-77d68fb5fc-gnpvg                   87m          21Mi
testkube-dashboard-794596b5dc-nxdvn                    1m           2Mi
testkube-minio-testkube-64cd475b94-glxxg               1m           98Mi
testkube-mongodb-6c9c5db4d5-4hr92                      61m          109Mi
testkube-operator-controller-manager-7788959c5-ddqml   10m          19Mi
NAME                                                   CPU(cores)   MEMORY(bytes)
6308b8f3016ae39e42614f66-c7fhl                         234m         413Mi
6308b8f7016ae39e42614f6a-dhkwd                         306m         421Mi
6308b8fa016ae39e42614f6c-gvwpf                         182m         391Mi
6308b8ff016ae39e42614f70-txgdl                         309m         426Mi
testkube-api-server-77d68fb5fc-gnpvg                   54m          20Mi
testkube-dashboard-794596b5dc-nxdvn                    1m           2Mi
testkube-minio-testkube-64cd475b94-glxxg               1m           98Mi
testkube-mongodb-6c9c5db4d5-4hr92                      111m         120Mi
testkube-operator-controller-manager-7788959c5-ddqml   20m          19Mi
```

### CODE REVIEW

**Review by vsukhin — APPROVED** [review]
nice

**Comment by vsukhin** [comment]
@tkonieczny Should we also change other values.yaml files, for demo, etc?

**Comment by tkonieczny** [comment]
I configured just the ones I think are more important. I will be trying to determine other ones - for example for dashboard, etc - I'm not sure how they should be configured yet.

**Review by exu — APPROVED** [review]

**Review by kylehodgetts — APPROVED** [review]

**Comment by kylehodgetts** [comment]
Does the chart version need to be bumped in `Chart.yaml`?

**Pull request merged**
